extern fun getchar (): int = "xgetchar"
extern fun puts (s: string): size_t = "xputs"
extern fun getcga (): [l:agz] (char @ l | ptr l) = "xgetcga"
extern fun pokeb (p : ptr, into: int, w: int): void = "xpokeb"
extern fun rand (): int = "xrand"
extern fun textmode {l:agz} (pf: char @ l | p : ptr l): void = "xtextmode"
